# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test2.proto',
  package='',
  serialized_pb=_b('\n\x0btest2.proto\"}\n\x08testinfo\x12\x10\n\x08\x64\x65vtype1\x18\x01 \x02(\x05\x12\x12\n\ndevidtest2\x18\x02 \x02(\x05\x12\x0f\n\x07unitid3\x18\x03 \x02(\x05\x12\x0e\n\x06\x63hlid4\x18\x04 \x02(\x05\x12\x12\n\x07testid5\x18\x05 \x01(\x05:\x01\x30\x12\x16\n\x0estepdata_test6\x18\x06 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TESTINFO = _descriptor.Descriptor(
  name='testinfo',
  full_name='testinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devtype1', full_name='testinfo.devtype1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devidtest2', full_name='testinfo.devidtest2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitid3', full_name='testinfo.unitid3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chlid4', full_name='testinfo.chlid4', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testid5', full_name='testinfo.testid5', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stepdata_test6', full_name='testinfo.stepdata_test6', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['testinfo'] = _TESTINFO

testinfo = _reflection.GeneratedProtocolMessageType('testinfo', (_message.Message,), dict(
  DESCRIPTOR = _TESTINFO,
  __module__ = 'test2_pb2'
  # @@protoc_insertion_point(class_scope:testinfo)
  ))
_sym_db.RegisterMessage(testinfo)


# @@protoc_insertion_point(module_scope)
